import { NextResponse } from "next/server";
import { unlink, writeFile } from "fs/promises";
import path from "path";
import { db } from "@/lib/db";
import { handler, HttpError, requireStaff } from "@/lib/guard";
import { audit } from "@/lib/audit";
import {
  ALLOWED_EXT,
  MAX_UPLOAD_BYTES,
  PUBLIC_PREFIX,
  UPLOAD_DIR,
  ensureUploadDir,
  isSafeFilename,
  listImages,
  looksLikeImage,
  safeFilenameFrom,
} from "@/lib/uploads";

export const runtime = "nodejs"; // needs the filesystem

/** The photo library — everything currently in public/uploads/menu/. */
export const GET = handler(async () => {
  await requireStaff("BRANCH_MANAGER", "KITCHEN", "CASHIER");
  return NextResponse.json({ images: await listImages() });
});

/**
 * Uploads one photo (multipart/form-data, field name "file").
 *
 * The stored filename is generated by us, never taken from the client, and the
 * bytes are sniffed rather than trusted — a .png extension on a script is the
 * classic way to get executable content onto a server.
 */
export const POST = handler(async (req: Request) => {
  const s = await requireStaff("BRANCH_MANAGER");

  const form = await req.formData().catch(() => null);
  const file = form?.get("file");
  if (!(file instanceof File)) throw new HttpError(400, "No file uploaded");

  if (file.size === 0) throw new HttpError(400, "That file is empty");
  if (file.size > MAX_UPLOAD_BYTES)
    throw new HttpError(
      413,
      `Image is too large (${Math.round(file.size / 1024 / 1024)} MB). Maximum is ${MAX_UPLOAD_BYTES / 1024 / 1024} MB.`
    );

  const ext = path.extname(file.name).toLowerCase();
  if (!(ALLOWED_EXT as readonly string[]).includes(ext))
    throw new HttpError(400, `Unsupported file type. Use ${ALLOWED_EXT.join(", ")}`);

  const buf = Buffer.from(await file.arrayBuffer());
  if (!looksLikeImage(buf, ext))
    throw new HttpError(400, "That file is not a real image, or is corrupted.");

  await ensureUploadDir();
  const name = safeFilenameFrom(file.name);
  // Defensive: safeFilenameFrom always produces a plain name, but this is the
  // last gate before a path touches the disk.
  if (!isSafeFilename(name)) throw new HttpError(400, "Could not build a safe filename");

  await writeFile(path.join(UPLOAD_DIR, name), buf);
  await audit({ uid: s.uid, name: s.name }, "MENU_IMAGE_UPLOADED", "MenuImage", name, {
    sizeKb: Math.round(buf.length / 1024),
  });

  return NextResponse.json({
    ok: true,
    image: { name, url: PUBLIC_PREFIX + encodeURIComponent(name), sizeKb: Math.round(buf.length / 1024) },
  });
});

/**
 * Deletes a photo. Refuses while any menu item still points at it, so the
 * dashboard cannot silently break live menu images.
 */
export const DELETE = handler(async (req: Request) => {
  const s = await requireStaff("BRANCH_MANAGER");
  const name = new URL(req.url).searchParams.get("name") ?? "";
  if (!isSafeFilename(name)) throw new HttpError(400, "Invalid filename");

  const url = PUBLIC_PREFIX + encodeURIComponent(name);
  const inUse = await db.menuItem.findMany({
    where: { imageUrl: url },
    select: { name: true },
    take: 5,
  });
  if (inUse.length > 0)
    throw new HttpError(
      409,
      `Still used by: ${inUse.map((i) => i.name).join(", ")}. Change those items first.`
    );

  try {
    await unlink(path.join(UPLOAD_DIR, name));
  } catch {
    throw new HttpError(404, "That image no longer exists");
  }
  await audit({ uid: s.uid, name: s.name }, "MENU_IMAGE_DELETED", "MenuImage", name, {});
  return NextResponse.json({ ok: true });
});
